# Generated by Django 6.0 on 2025-12-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255, verbose_name='Текст')),
                ('action_type', models.CharField(choices=[('copy', 'Скопировать текст'), ('link', 'Перейти по ссылке')], default='copy', max_length=10, verbose_name='Тип действия')),
                ('copy_data', models.CharField(blank=True, max_length=255, verbose_name='Текст скопируется при нажатии')),
                ('link_data', models.CharField(blank=True, max_length=255, verbose_name='Ссылка для перехода')),
            ],
            options={
                'verbose_name': 'Информацию в футере сайта',
                'verbose_name_plural': 'Информация в футере сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.BooleanField(default=False, verbose_name='Режим технических работ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'permissions': [('bypass_maintenance', 'Может обходить режим техработ')],
            },
        ),
    ]
