# Generated by Django 6.0 on 2025-12-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('admin', 'Сообщение от администрации'), ('post_edited', 'Пост отредактирован'), ('post_pinned', 'Пост закреплён'), ('post_unpinned', 'Пост откреплён'), ('post_deleted', 'Пост удален'), ('topic_deleted', 'Топик удалён'), ('topic_pinned', 'Топик закреплен'), ('topic_unpinned', 'Топик откреплен'), ('topic_closed', 'Обсуждение закрыто'), ('topic_unclosed', 'Обсуждение открыто'), ('group_added', 'Вам выдана роль'), ('group_removed', 'Ваша роль была отозвана'), ('groups_cleared', 'Роли очищены'), ('permission_added', 'Вам выдано право'), ('permission_removed', 'Ваше право было отозвано'), ('permissions_cleared', 'Права очищены'), ('poll_finished', 'Голосование завершено'), ('warning', 'Важное уведомление!'), ('moderation_alert', 'Зафиксировано нарушение'), ('post_blocked', 'Ваш пост был автоматически скрыт системой'), ('other', 'Другое'), ('user', 'User'), ('system', 'System')], default='user', help_text='USER | SYSTEM', max_length=20, verbose_name='Тип отправителя')),
                ('type', models.CharField(choices=[('admin', 'Сообщение от администрации'), ('post_edited', 'Пост отредактирован'), ('post_pinned', 'Пост закреплён'), ('post_unpinned', 'Пост откреплён'), ('post_deleted', 'Пост удален'), ('topic_deleted', 'Топик удалён'), ('topic_pinned', 'Топик закреплен'), ('topic_unpinned', 'Топик откреплен'), ('topic_closed', 'Обсуждение закрыто'), ('topic_unclosed', 'Обсуждение открыто'), ('group_added', 'Вам выдана роль'), ('group_removed', 'Ваша роль была отозвана'), ('groups_cleared', 'Роли очищены'), ('permission_added', 'Вам выдано право'), ('permission_removed', 'Ваше право было отозвано'), ('permissions_cleared', 'Права очищены'), ('poll_finished', 'Голосование завершено'), ('warning', 'Важное уведомление!'), ('moderation_alert', 'Зафиксировано нарушение'), ('post_blocked', 'Ваш пост был автоматически скрыт системой'), ('other', 'Другое'), ('user', 'User'), ('system', 'System')], help_text='НЕ ВЫБИРАТЬ USER И SYSTEM ЭТО ВЫЗОВЕТ ОШИБКУ', max_length=32, verbose_name='Тип уведомления')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('data', models.JSONField(blank=True, default=dict, help_text='В формате JSON', verbose_name='Данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Уведомление привязано к')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Кому отправлено')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'), models.Index(fields=['user', 'id'], name='notificatio_user_id_ced90b_idx'), models.Index(fields=['type'], name='notificatio_type_94f703_idx')],
            },
        ),
    ]
