"""
Django settings for forum project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Выбираем, какой .env файл грузить
ENVIRONMENT = os.getenv('DJANGO_ENV', 'local')  # 'local', 'stage', 'prod'

# Если нет файла, fallback на локальный
env_file = {
    'local': '.env.local',
    'stage': '.env.stage',
    'prod': '.env.prod'
}.get(ENVIRONMENT, '.env.local')

env = environ.Env(
    DEBUG=(bool, False)
)

# Загружаем .env
env.read_env(os.path.join(BASE_DIR, env_file))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# РЕЖИМ ТЕХНИЧЕСКИХ РАБОТ, ПЕРЕД ВКЛЮЧЕНИЕМ ОБЯЗАТЕЛЬНО ВОЙТИ КАК SUPERUSER ИЛИ СО СПЕЦИАЛЬНЫМ ПРАВОМ
MAINTENANCE_MODE = True

# DEV_IPS = [
#     '127.0.0.1', 
#     '46.147.98.45', #WI-FI дома
#     '188.43.251.254', #WI-FI на работе
#     '91.195.137.206', #hope
#     #'94.50.108.45', #4eknutiy
#     #'178.206.251.79', #user
#     #'95.110.85.15' #user
#     ]

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'tailwind',
    'theme',
    'main',
    'news',
    'axes',
    'notification',
    'core',
    'user.apps.UserConfig',
    'forum_app',
    'forum_filter',
    'django_ckeditor_5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
]

# if DEBUG:
#     INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.MaintenanceModeMiddleware',
    'core.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.UpdateLastSeenMiddleware', 
    'user.middleware.RequireServernameMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
]

ANONYMOUS_USER_NAME = None

AXES_FAILURE_LIMIT = 5          # попыток
AXES_COOLOFF_TIME = 1           # часы
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']
AXES_RESET_ON_SUCCESS = True

CKEDITOR_5_CONFIGS = {
    'default': {
        'language': 'ru',
        'toolbar': [
                    'heading',
            '|',
            'bold', 'italic', 'underline', 'strikethrough',
            'subscript', 'superscript', 'code',
            '|',
            'fontSize', 'fontFamily',
            'fontColor', 'fontBackgroundColor',
            'highlight',
            '|',
            'alignment',
            '|',
            'link',
            'bulletedList', 'numberedList', 'todoList',
            '|',
            'outdent', 'indent',
            '|',
            'blockQuote', 'codeBlock',
            '|',
            'insertTable',
            'mediaEmbed',
            'imageUpload',
            '|',
            'removeFormat',
            'sourceEditing',
            'comment',
            'trackChanges',
            'horizontalLine',
            '|',
            'undo', 'redo'
        ],
        
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Параграф'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Заголовок 1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Заголовок 2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Заголовок 3'},
            ]
        },

        'htmlSupport': {
            'allow': [
                {
                    'name': '/.*/',
                    'attributes': True,
                    'classes': True,
                    'styles': True
                }
            ]
        },

        'image': {
            'toolbar': [
                'imageTextAlternative',
                'imageStyle:inline',
                'imageStyle:block',
                'imageStyle:side'
            ]
        },

        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells'
            ]
        },

        'mediaEmbed': {
            'previewsInData': True
        },
    }
}

# if DEBUG:
#     MIDDLEWARE += ["django_browser_reload.middleware.BrowserReloadMiddleware",]

ROOT_URLCONF = 'forum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notification.context_processors.notifications',
                'main.context_processors.footer_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'forum.wsgi.application'

TAILWIND_APP_NAME = 'theme'
if os.name == 'nt':
    NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd' #TEMPORARY!
else:
    NPM_BIN_PATH = '/usr/bin/npm'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.name == 'nt':
    DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env('DB_NAME'),
                'USER': env('DB_USER'),
                'PASSWORD': env('DB_PASSWORD'),
                'HOST': env('DB_HOST'),
                'PORT': env('DB_PORT'),
            }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


