# Generated by Django 6.0 on 2025-12-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpAccardion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024, verbose_name='Вопрос')),
                ('text', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Пункт в разделе помощь',
                'verbose_name_plural': 'Пункты в разделе помощь',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(default='full', help_text='[от 1 до 100] Значение указывается в процентах ширины экрана', verbose_name='Ширина')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Картинка')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='banner/small/')),
            ],
            options={
                'verbose_name': 'Баннер на главной',
                'verbose_name_plural': 'Баннер на главной',
            },
        ),
        migrations.CreateModel(
            name='MainRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='VoteBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('multiple', models.BooleanField(default=False, verbose_name='Множественный выбор')),
                ('active', models.BooleanField(default=True, verbose_name='Голосование активно')),
                ('closed', models.BooleanField(default=False, help_text='(не отображается)', verbose_name='Голосование закрыто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('notified_finished', models.BooleanField(default=False, verbose_name='Уведомления об окончании разосланы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
                'permissions': [('can_vote', 'Может голосовать')],
            },
        ),
        migrations.CreateModel(
            name='VoteBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_item', to='main.votebox', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Опцию голосования',
                'verbose_name_plural': 'Опции голосований',
            },
        ),
        migrations.AddField(
            model_name='votebox',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.voteboxitem', verbose_name='Выбран вариант'),
        ),
        migrations.CreateModel(
            name='VoteBoxVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_box', to='main.votebox', verbose_name='Голосование')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_item_vote', to='main.voteboxitem', verbose_name='Выбор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'constraints': [models.UniqueConstraint(fields=('box', 'item', 'user'), name='unique_vote_per_item')],
            },
        ),
    ]
