# Generated by Django 6.0 on 2025-12-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, help_text='Tailwind-классы', null=True, verbose_name='Стили роли')),
                ('display_priority', models.IntegerField(default=1, help_text='Приоритет отображения, если групп несколько будет отображена в чате самая значимая', verbose_name='Приоритет')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(blank=True, max_length=255, verbose_name='Отображаемое имя')),
                ('servername', models.CharField(blank=True, max_length=255, verbose_name='Ник в игре')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, default='users/avatar/0.jpg', upload_to='users/avatar/', verbose_name='Аватар')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'permissions': [('edit_profile', 'Редактировать чужие профили'), ('edit_user_perms', 'Менять права'), ('can_edit_profile_gropus', 'Редактировать роли'), ('see_full_profile', 'Видеть полный профиль'), ('safety', 'Защита от редактирования')],
            },
        ),
    ]
