from django import template

register = template.Library()

@register.filter
def safe_classes(value):
    """
    Оставляет только разрешённые Tailwind-классы.
    Добавляй сюда все используемые классы.
    """
    allowed = [
        'bg-sky-500','p-1','px-3','font-bold','rounded-full','animate-bounce','uppercase', 'w-fit', 'not-hover:animate-bounce','hover:animate-ping','cursor-pointer',
        'w-full',
        'md:w-1',
        'md:w-1.5',
        'md:w-2',
        'md:w-2.5',
        'md:w-3',
        'md:w-3.5',
        'md:w-4',
        'md:w-4.5',
        'md:w-5',
        'md:w-5.5',
        'md:w-6',
        'md:w-6.5',
        'md:w-7',
        'md:w-7.5',
        'md:w-8',
        'md:w-8.5',
        'md:w-9',
        'md:w-9.5',
        'md:w-10',
        'md:w-11',
        'md:w-12',
        'md:w-13',
        'md:w-14',
        'md:w-15',
        'md:w-16',
        'md:w-17',
        'md:w-18',
        'md:w-19',
        'md:w-20',
        'md:w-25',
        'md:w-30',
        'md:w-35',
        'md:w-40',
        'md:w-45',
        'md:w-50',
        'md:w-55',
        'md:w-60',
        'md:w-65',
        'md:w-70',
        'md:w-75',
        'md:w-80',
        'md:w-85',
        'md:w-90',
        'md:w-95',
        'md:w-100',
        'md:w-150',
        'md:w-200',
        'md:w-250',
        'md:w-300',
        'md:w-350',
        'md:w-400',
        'md:w-450',
        'md:w-500',
        'md:w-550',
        'md:w-600',
        'md:w-650',
        'md:w-700',
        'md:w-750',
        'md:w-800',
        'md:w-850',
        'md:w-900',
        'md:w-950',
        'md:w-1000',
        'md:w-full',
        'md:w-1/2',
        'md:w-1/3',
        'md:w-2/3',
        'md:w-1/4',
        'md:w-3/4',
        'md:w-1/5',
        'md:w-2/5',
        'md:w-3/5',
        'md:w-4/5',
        'md:w-1/6',
        'md:w-5/6',
    ]
    if not value:
        return ''
    return ' '.join([cls for cls in value.split() if cls in allowed])