# Generated by Django 6.0 on 2025-12-21 13:58

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Вид ссылки')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображается')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'permissions': [('can_see_hidden_cats', 'Видеть скрытые категории'), ('can_hide_cats', 'Скрывать категории')],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображается')),
                ('closed', models.BooleanField(default=False, verbose_name='Тема закрыта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum_app.forumcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
                'permissions': [('can_pin_topic', 'Закреплять топики'), ('can_see_hidden_topics', 'Видеть скрытые топики'), ('can_hide_topic', 'Скрывать топики'), ('can_close_topic', 'Закрывать топики'), ('can_delete_topic', 'Удалять топики'), ('can_create_topic', 'Создавать новые темы')],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст поста')),
                ('pinned', models.BooleanField(default=False, verbose_name='Закреплен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('edited', models.BooleanField(default=False, verbose_name='Изменен')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображается')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален пользователем')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum_app.forumtopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'permissions': [('can_see_hidden_post', 'Видеть скрытые посты'), ('can_hide_post', 'Скрывать посты'), ('can_pin_post', 'Закреплять посты'), ('can_edit_post', 'Редактировать посты'), ('can_edit_another_post', 'Редактировать чужие посты'), ('can_delete_post', 'Удалять посты'), ('can_really_delete_post', 'Реально удалять посты'), ('can_post', 'Писать на форуме'), ('can_post_closed', 'Писать даже в закрытые темы')],
            },
        ),
    ]
